# -*- coding: utf-8 -*-
"""plot target and predicted.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aWisWcvIvWamGIpr-vxl_l4jrNWodxlo
"""

import matplotlib.pyplot as plt
import numpy as np
y_test=[3.642, 1.46, 1.565, 1.493, 1.153,	2.84,1.424, 1.435, 1.25, 1.212, 1.083, 1.465,	1.157,	1.492,1.14, 1.087, 1.066, 1.218, 1.19,0.917]
y_pred=[3.81478,1.45441,1.45612,1.64185,1.36379,2.76866,1.17138,1.36276,1.15301,0.963753,1.10474,1.48016,1.14377,1.81985,1.19259,1.07195,1.06305,1.26559,1.18977,1.06841]
t = np.arange(0, 20, 1)
plt.plot(t,y_test,'b',t,y_pred,'r--')
plt.legend(['Target output', 'Predicted output'])
#plt.ylabel('some numbers')
plt.show()

t = np.arange(0, 20, 1)
print(t)